name: Deploy Next.js App

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "18"

      - name: Install dependencies
        run: npm install

      - name: Run tests with coverage
        run: npm run test -- --coverage --watchAll=false

      - name: Show coverage directory
        run: ls -R coverage # 显示覆盖率目录，以确认文件是否存在

      - name: Generate coverage badge
        run: npm run coverage-badge # 确保生成覆盖率徽章

      - name: Build the project
        run: npm run build

      - name: Build Docker image
        run: docker build -t derek11428/app-store:latest .

      - name: List Docker images
        run: docker images

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Push Docker image
        run: docker push derek11428/app-store:latest

      - name: Update README with version and coverage badge
        run: |
          VERSION=$(node -p "require('./package.json').version")
          sed -i "s|<!--version-->|![Version](https://img.shields.io/badge/version-$VERSION-blue)|g" README.md

          if [ -f coverage/badge.svg ]; then
            COVERAGE_BADGE=$(cat coverage/badge.svg | base64)
            echo "![Coverage](data:image/svg+xml;base64,$COVERAGE_BADGE)" > coverage-badge.svg
            sed -i "s|<!--coverage-->|![Coverage](coverage-badge.svg)|g" README.md
          else
            echo "Coverage badge not found!"  # 输出调试信息
          fi

      - name: Commit and push changes to README
        run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "github-actions"
          git add README.md coverage-badge.svg
          git commit -m "Update README with version and coverage badge" || echo "No changes to commit"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
