name: Deploy Next.js App

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "18"

      - name: Install dependencies
        run: npm install

      - name: Build the project
        run: npm run build

      - name: Build Docker image
        run: docker build -t derek11428/app-store:latest .

      - name: List Docker images
        run: docker images

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Push Docker image
        run: docker push derek11428/app-store:latest

      - name: Update README with version and coverage
        run: |
          echo "Version: $(node -p "require('./package.json').version")" >> README.md
          echo "Coverage: $(npm run test -- --coverage --watchAll=false --reporters=lcov)" >> README.md

      - name: Commit and push changes to README
        run: |
          git config --local user.email "your-email@example.com"
          git config --local user.name "Your Name"
          git add README.md
          git commit -m "Update README with version and coverage"
          git push
